// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "./client";
import type {
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  AuthJwtLogoutErrors,
  RegisterRegisterData,
  RegisterRegisterResponses,
  RegisterRegisterErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  ReadDocListData,
  ReadDocListResponses,
  CreateDocData,
  CreateDocResponses,
  CreateDocErrors,
  ReadApiKeyData,
  ReadApiKeyResponses,
  SaveApiKeyData,
  SaveApiKeyResponses,
  DeleteApiKeyData,
  DeleteApiKeyResponses,
  DeleteApiKeyErrors,
  UploadDocFileData,
  UploadDocFileResponses,
  UploadDocFileErrors,
  DeleteDocData,
  DeleteDocResponses,
  DeleteDocErrors,
  ReadDocList2Data,
  ReadDocList2Responses,
  CreateDoc2Data,
  CreateDoc2Responses,
  CreateDoc2Errors,
  ReadApiKey2Data,
  ReadApiKey2Responses,
  SaveApiKey2Data,
  SaveApiKey2Responses,
  DeleteApiKey2Data,
  DeleteApiKey2Responses,
  DeleteApiKey2Errors,
  UploadDocFile2Data,
  UploadDocFile2Responses,
  UploadDocFile2Errors,
  DeleteDoc2Data,
  DeleteDoc2Responses,
  DeleteDoc2Errors,
  ReadPipelineData,
  ReadPipelineResponses,
  AddPipelineData,
  AddPipelineResponses,
  AddPipelineErrors,
  ReadConversionPipelineData,
  ReadConversionPipelineResponses,
  ReadConversionPipelineErrors,
  AddConversionPipelineData,
  AddConversionPipelineResponses,
  AddConversionPipelineErrors,
  RunConversionPipelineData,
  RunConversionPipelineResponses,
  RunConversionPipelineErrors,
  RunConversionPipeline2Data,
  RunConversionPipeline2Responses,
  ReadChunkingPipelineData,
  ReadChunkingPipelineResponses,
  ReadChunkingPipelineErrors,
  AddChunkingPipelineData,
  AddChunkingPipelineResponses,
  AddChunkingPipelineErrors,
  RunChunkingPipelineData,
  RunChunkingPipelineResponses,
  RunChunkingPipelineErrors,
  ReadChunkingLevelsData,
  ReadChunkingLevelsResponses,
  ReadChunkingLevelsErrors,
  ReadChunkingResultsData,
  ReadChunkingResultsResponses,
  ReadChunkingResultsErrors,
  AddChunkingResultsData,
  AddChunkingResultsResponses,
  AddChunkingResultsErrors,
  ReadMarkdownResultsData,
  ReadMarkdownResultsResponses,
  ReadMarkdownResultsErrors,
  RunChunkingPipeline2Data,
  RunChunkingPipeline2Responses,
  ReadExtractionPipelineData,
  ReadExtractionPipelineResponses,
  ReadExtractionPipelineErrors,
  AddExtractionPipelineData,
  AddExtractionPipelineResponses,
  AddExtractionPipelineErrors,
  RunExtractionPipelineData,
  RunExtractionPipelineResponses,
  RunExtractionPipelineErrors,
  ExtractAllData,
  ExtractAllResponses,
  ReadRetrievalPipelineData,
  ReadRetrievalPipelineResponses,
  ReadRetrievalPipelineErrors,
  AddRetrievalPipelineData,
  AddRetrievalPipelineResponses,
  AddRetrievalPipelineErrors,
  ExportPipelineData,
  ExportPipelineResponses,
  ExportPipelineErrors,
  ExportAllData,
  ExportAllResponses,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Doc List
 */
export const readDocList = <ThrowOnError extends boolean = false>(
  options?: Options<ReadDocListData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadDocListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
  });
};

/**
 * Create Doc
 */
export const createDoc = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDocResponses,
    CreateDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Api Key
 */
export const readApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<ReadApiKeyData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/",
    ...options,
  });
};

/**
 * Save Api Key
 */
export const saveApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<SaveApiKeyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SaveApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/",
    ...options,
  });
};

/**
 * Delete Api Key
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiKeyData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiKeyResponses,
    DeleteApiKeyErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/{key_id}",
    ...options,
  });
};

/**
 * Upload Doc File
 */
export const uploadDocFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFileData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadDocFileResponses,
    UploadDocFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/uploads/{doc_id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete Doc
 */
export const deleteDoc = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocResponses,
    DeleteDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{doc_id}",
    ...options,
  });
};

/**
 * Read Doc List
 */
export const readDocList2 = <ThrowOnError extends boolean = false>(
  options?: Options<ReadDocList2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadDocList2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/",
    ...options,
  });
};

/**
 * Create Doc
 */
export const createDoc2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateDoc2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDoc2Responses,
    CreateDoc2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Api Key
 */
export const readApiKey2 = <ThrowOnError extends boolean = false>(
  options?: Options<ReadApiKey2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadApiKey2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/",
    ...options,
  });
};

/**
 * Save Api Key
 */
export const saveApiKey2 = <ThrowOnError extends boolean = false>(
  options?: Options<SaveApiKey2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SaveApiKey2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/",
    ...options,
  });
};

/**
 * Delete Api Key
 */
export const deleteApiKey2 = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiKey2Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiKey2Responses,
    DeleteApiKey2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/{key_id}",
    ...options,
  });
};

/**
 * Upload Doc File
 */
export const uploadDocFile2 = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFile2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadDocFile2Responses,
    UploadDocFile2Errors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/uploads/{doc_id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete Doc
 */
export const deleteDoc2 = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDoc2Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDoc2Responses,
    DeleteDoc2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{doc_id}",
    ...options,
  });
};

/**
 * Read Pipeline
 */
export const readPipeline = <ThrowOnError extends boolean = false>(
  options?: Options<ReadPipelineData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadPipelineResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/pipeline/data/",
    ...options,
  });
};

/**
 * Add Pipeline
 */
export const addPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddPipelineResponses,
    AddPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/pipeline/data/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Conversion Pipeline
 */
export const readConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadConversionPipelineResponses,
    ReadConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Conversion Pipeline
 */
export const addConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddConversionPipelineResponses,
    AddConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Conversion Pipeline
 */
export const runConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunConversionPipelineResponses,
    RunConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{doc_id}/run",
    ...options,
  });
};

/**
 * Run Conversion Pipeline
 */
export const runConversionPipeline2 = <ThrowOnError extends boolean = false>(
  options?: Options<RunConversionPipeline2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RunConversionPipeline2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/run",
    ...options,
  });
};

/**
 * Read Chunking Pipeline
 */
export const readChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingPipelineResponses,
    ReadChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Chunking Pipeline
 */
export const addChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddChunkingPipelineResponses,
    AddChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Chunking Pipeline
 */
export const runChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunChunkingPipelineResponses,
    RunChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/run",
    ...options,
  });
};

/**
 * Read Chunking Levels
 */
export const readChunkingLevels = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingLevelsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingLevelsResponses,
    ReadChunkingLevelsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/levels",
    ...options,
  });
};

/**
 * Read Chunking Results
 */
export const readChunkingResults = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingResultsResponses,
    ReadChunkingResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/results",
    ...options,
  });
};

/**
 * Add Chunking Results
 */
export const addChunkingResults = <ThrowOnError extends boolean = false>(
  options: Options<AddChunkingResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddChunkingResultsResponses,
    AddChunkingResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/results",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Markdown Results
 */
export const readMarkdownResults = <ThrowOnError extends boolean = false>(
  options: Options<ReadMarkdownResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadMarkdownResultsResponses,
    ReadMarkdownResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/markdown",
    ...options,
  });
};

/**
 * Run Chunking Pipeline
 */
export const runChunkingPipeline2 = <ThrowOnError extends boolean = false>(
  options?: Options<RunChunkingPipeline2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RunChunkingPipeline2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/run",
    ...options,
  });
};

/**
 * Read Extraction Pipeline
 */
export const readExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadExtractionPipelineResponses,
    ReadExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Extraction Pipeline
 */
export const addExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddExtractionPipelineResponses,
    AddExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Extraction Pipeline
 */
export const runExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunExtractionPipelineResponses,
    RunExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{doc_id}/run",
    ...options,
  });
};

/**
 * Extract All
 */
export const extractAll = <ThrowOnError extends boolean = false>(
  options?: Options<ExtractAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ExtractAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/run",
    ...options,
  });
};

/**
 * Read Retrieval Pipeline
 */
export const readRetrievalPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadRetrievalPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadRetrievalPipelineResponses,
    ReadRetrievalPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Retrieval Pipeline
 */
export const addRetrievalPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddRetrievalPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddRetrievalPipelineResponses,
    AddRetrievalPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Export Pipeline
 */
export const exportPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ExportPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportPipelineResponses,
    ExportPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{doc_id}/export",
    ...options,
  });
};

/**
 * Export All
 * 1. Runs Embeddings for each doc_id where exported=0
 * 2. Bundles all retrieval pipelines and exports them to the MainPipeline table
 */
export const exportAll = <ThrowOnError extends boolean = false>(
  options?: Options<ExportAllData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ExportAllResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/run",
    ...options,
  });
};
