// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "./client";
import type {
  AuthJwtLoginData,
  AuthJwtLoginResponses,
  AuthJwtLoginErrors,
  AuthJwtLogoutData,
  AuthJwtLogoutResponses,
  AuthJwtLogoutErrors,
  RegisterRegisterData,
  RegisterRegisterResponses,
  RegisterRegisterErrors,
  ResetForgotPasswordData,
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ResetResetPasswordData,
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  VerifyRequestTokenData,
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  VerifyVerifyData,
  VerifyVerifyResponses,
  VerifyVerifyErrors,
  UsersCurrentUserData,
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUserData,
  UsersUserResponses,
  UsersUserErrors,
  UsersPatchUserData,
  UsersPatchUserResponses,
  UsersPatchUserErrors,
  ExportProjectData,
  ExportProjectResponses,
  ExportProjectErrors,
  LoadProjectData,
  LoadProjectResponses,
  LoadProjectErrors,
  ListSavedProjectsData,
  ListSavedProjectsResponses,
  ListExportedProjectsData,
  ListExportedProjectsResponses,
  CreateProjectData,
  CreateProjectResponses,
  SetProjectData,
  SetProjectResponses,
  SetProjectErrors,
  DeleteProjectData,
  DeleteProjectResponses,
  DeleteProjectErrors,
  ReadEvaluatorData,
  ReadEvaluatorResponses,
  AddEvaluatorData,
  AddEvaluatorResponses,
  AddEvaluatorErrors,
  ReadApiKeyData,
  ReadApiKeyResponses,
  SaveApiKeyData,
  SaveApiKeyResponses,
  DeleteApiKeyData,
  DeleteApiKeyResponses,
  DeleteApiKeyErrors,
  ReadDocListData,
  ReadDocListResponses,
  ReadDocListErrors,
  CreateDocData,
  CreateDocResponses,
  CreateDocErrors,
  UploadDocFileData,
  UploadDocFileResponses,
  UploadDocFileErrors,
  DeleteDocData,
  DeleteDocResponses,
  DeleteDocErrors,
  ExportDocPipelineData,
  ExportDocPipelineResponses,
  ExportDocPipelineErrors,
  LoadDocPipelineData,
  LoadDocPipelineResponses,
  LoadDocPipelineErrors,
  ListDocPipelinesData,
  ListDocPipelinesResponses,
  DeleteDocPipelineData,
  DeleteDocPipelineResponses,
  DeleteDocPipelineErrors,
  ReadApiKey2Data,
  ReadApiKey2Responses,
  SaveApiKey2Data,
  SaveApiKey2Responses,
  DeleteApiKey2Data,
  DeleteApiKey2Responses,
  DeleteApiKey2Errors,
  ReadDocList2Data,
  ReadDocList2Responses,
  ReadDocList2Errors,
  CreateDoc2Data,
  CreateDoc2Responses,
  CreateDoc2Errors,
  UploadDocFile2Data,
  UploadDocFile2Responses,
  UploadDocFile2Errors,
  DeleteDoc2Data,
  DeleteDoc2Responses,
  DeleteDoc2Errors,
  ExportDocPipeline2Data,
  ExportDocPipeline2Responses,
  ExportDocPipeline2Errors,
  LoadDocPipeline2Data,
  LoadDocPipeline2Responses,
  LoadDocPipeline2Errors,
  ListDocPipelines2Data,
  ListDocPipelines2Responses,
  DeleteDocPipeline2Data,
  DeleteDocPipeline2Responses,
  DeleteDocPipeline2Errors,
  ReadGeneratorData,
  ReadGeneratorResponses,
  AddGeneratorData,
  AddGeneratorResponses,
  AddGeneratorErrors,
  ReadRetrieversData,
  ReadRetrieversResponses,
  ReadRetrieversErrors,
  AddRetrieversData,
  AddRetrieversResponses,
  AddRetrieversErrors,
  ReadColorsData,
  ReadColorsResponses,
  AddColorsData,
  AddColorsResponses,
  AddColorsErrors,
  ReadThemesData,
  ReadThemesResponses,
  AddThemesData,
  AddThemesResponses,
  AddThemesErrors,
  ReadConversionPipelineData,
  ReadConversionPipelineResponses,
  ReadConversionPipelineErrors,
  AddConversionPipelineData,
  AddConversionPipelineResponses,
  AddConversionPipelineErrors,
  RunConversionPipelineData,
  RunConversionPipelineResponses,
  RunConversionPipelineErrors,
  ConvertAllData,
  ConvertAllResponses,
  ConvertAllErrors,
  ReadChunkingPipelineData,
  ReadChunkingPipelineResponses,
  ReadChunkingPipelineErrors,
  AddChunkingPipelineData,
  AddChunkingPipelineResponses,
  AddChunkingPipelineErrors,
  RunChunkingPipelineData,
  RunChunkingPipelineResponses,
  RunChunkingPipelineErrors,
  ReadChunkingLevelsData,
  ReadChunkingLevelsResponses,
  ReadChunkingLevelsErrors,
  ReadChunkingResultsData,
  ReadChunkingResultsResponses,
  ReadChunkingResultsErrors,
  AddChunkingResultsData,
  AddChunkingResultsResponses,
  AddChunkingResultsErrors,
  ReadMarkdownResultsData,
  ReadMarkdownResultsResponses,
  ReadMarkdownResultsErrors,
  ChunkAllData,
  ChunkAllResponses,
  ChunkAllErrors,
  ReadExtractionPipelineData,
  ReadExtractionPipelineResponses,
  ReadExtractionPipelineErrors,
  AddExtractionPipelineData,
  AddExtractionPipelineResponses,
  AddExtractionPipelineErrors,
  RunExtractionPipelineData,
  RunExtractionPipelineResponses,
  RunExtractionPipelineErrors,
  ReadRetrievalPipelineData,
  ReadRetrievalPipelineResponses,
  ReadRetrievalPipelineErrors,
  AddRetrievalPipelineData,
  AddRetrievalPipelineResponses,
  AddRetrievalPipelineErrors,
  ExportPipelineData,
  ExportPipelineResponses,
  ExportPipelineErrors,
  ExportAllData,
  ExportAllResponses,
  ExportAllErrors,
  RagQueryToolData,
  RagQueryToolResponses,
  RagQueryToolErrors,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/auth/jwt/logout",
    ...options,
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Export Project
 */
export const exportProject = <ThrowOnError extends boolean = false>(
  options: Options<ExportProjectData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportProjectResponses,
    ExportProjectErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/export/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Load Project
 */
export const loadProject = <ThrowOnError extends boolean = false>(
  options: Options<LoadProjectData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoadProjectResponses,
    LoadProjectErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/load/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Saved Projects
 */
export const listSavedProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ListSavedProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListSavedProjectsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/list/saved/",
    ...options,
  });
};

/**
 * List Exported Projects
 */
export const listExportedProjects = <ThrowOnError extends boolean = false>(
  options?: Options<ListExportedProjectsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListExportedProjectsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/list/exported/",
    ...options,
  });
};

/**
 * Create Project
 */
export const createProject = <ThrowOnError extends boolean = false>(
  options?: Options<CreateProjectData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateProjectResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/",
    ...options,
  });
};

/**
 * Set Project
 */
export const setProject = <ThrowOnError extends boolean = false>(
  options: Options<SetProjectData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SetProjectResponses,
    SetProjectErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/set/{project_id}",
    ...options,
  });
};

/**
 * Delete Project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProjectData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteProjectResponses,
    DeleteProjectErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/{project_id}",
    ...options,
  });
};

/**
 * Read Evaluator
 */
export const readEvaluator = <ThrowOnError extends boolean = false>(
  options?: Options<ReadEvaluatorData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadEvaluatorResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/evaluator/",
    ...options,
  });
};

/**
 * Add Evaluator
 */
export const addEvaluator = <ThrowOnError extends boolean = false>(
  options: Options<AddEvaluatorData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddEvaluatorResponses,
    AddEvaluatorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/projects/evaluator/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Api Key
 */
export const readApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<ReadApiKeyData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/",
    ...options,
  });
};

/**
 * Save Api Key
 */
export const saveApiKey = <ThrowOnError extends boolean = false>(
  options?: Options<SaveApiKeyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SaveApiKeyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/",
    ...options,
  });
};

/**
 * Delete Api Key
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiKeyData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiKeyResponses,
    DeleteApiKeyErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/api_keys/{key_id}",
    ...options,
  });
};

/**
 * Read Doc List
 */
export const readDocList = <ThrowOnError extends boolean = false>(
  options: Options<ReadDocListData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadDocListResponses,
    ReadDocListErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}",
    ...options,
  });
};

/**
 * Create Doc
 */
export const createDoc = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDocResponses,
    CreateDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Upload Doc File
 */
export const uploadDocFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFileData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadDocFileResponses,
    UploadDocFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}/uploads/{doc_id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete Doc
 */
export const deleteDoc = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocResponses,
    DeleteDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}/deletes/{doc_id}",
    ...options,
  });
};

/**
 * Export Doc Pipeline
 */
export const exportDocPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ExportDocPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportDocPipelineResponses,
    ExportDocPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}/pipelines/export/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Load Doc Pipeline
 */
export const loadDocPipeline = <ThrowOnError extends boolean = false>(
  options: Options<LoadDocPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoadDocPipelineResponses,
    LoadDocPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{project_id}/pipelines/load/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Doc Pipelines
 */
export const listDocPipelines = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocPipelinesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListDocPipelinesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/list/",
    ...options,
  });
};

/**
 * Delete Doc Pipeline
 */
export const deleteDocPipeline = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocPipelineResponses,
    DeleteDocPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/{pipeline_id}",
    ...options,
  });
};

/**
 * Read Api Key
 */
export const readApiKey2 = <ThrowOnError extends boolean = false>(
  options?: Options<ReadApiKey2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadApiKey2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/",
    ...options,
  });
};

/**
 * Save Api Key
 */
export const saveApiKey2 = <ThrowOnError extends boolean = false>(
  options?: Options<SaveApiKey2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SaveApiKey2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/",
    ...options,
  });
};

/**
 * Delete Api Key
 */
export const deleteApiKey2 = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiKey2Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteApiKey2Responses,
    DeleteApiKey2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/api_keys/{key_id}",
    ...options,
  });
};

/**
 * Read Doc List
 */
export const readDocList2 = <ThrowOnError extends boolean = false>(
  options: Options<ReadDocList2Data, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadDocList2Responses,
    ReadDocList2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}",
    ...options,
  });
};

/**
 * Create Doc
 */
export const createDoc2 = <ThrowOnError extends boolean = false>(
  options: Options<CreateDoc2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDoc2Responses,
    CreateDoc2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Upload Doc File
 */
export const uploadDocFile2 = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFile2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    UploadDocFile2Responses,
    UploadDocFile2Errors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}/uploads/{doc_id}",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });
};

/**
 * Delete Doc
 */
export const deleteDoc2 = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDoc2Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDoc2Responses,
    DeleteDoc2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}/deletes/{doc_id}",
    ...options,
  });
};

/**
 * Export Doc Pipeline
 */
export const exportDocPipeline2 = <ThrowOnError extends boolean = false>(
  options: Options<ExportDocPipeline2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportDocPipeline2Responses,
    ExportDocPipeline2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}/pipelines/export/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Load Doc Pipeline
 */
export const loadDocPipeline2 = <ThrowOnError extends boolean = false>(
  options: Options<LoadDocPipeline2Data, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoadDocPipeline2Responses,
    LoadDocPipeline2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/{project_id}/pipelines/load/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Doc Pipelines
 */
export const listDocPipelines2 = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocPipelines2Data, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListDocPipelines2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/pipelines/list/",
    ...options,
  });
};

/**
 * Delete Doc Pipeline
 */
export const deleteDocPipeline2 = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocPipeline2Data, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocPipeline2Responses,
    DeleteDocPipeline2Errors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api_keys/pipelines/{pipeline_id}",
    ...options,
  });
};

/**
 * Read Generator
 */
export const readGenerator = <ThrowOnError extends boolean = false>(
  options?: Options<ReadGeneratorData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadGeneratorResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/generator/",
    ...options,
  });
};

/**
 * Add Generator
 */
export const addGenerator = <ThrowOnError extends boolean = false>(
  options: Options<AddGeneratorData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddGeneratorResponses,
    AddGeneratorErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/generator/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Retrievers
 */
export const readRetrievers = <ThrowOnError extends boolean = false>(
  options: Options<ReadRetrieversData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadRetrieversResponses,
    ReadRetrieversErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/{project_id}/retrievers/",
    ...options,
  });
};

/**
 * Add Retrievers
 * router = retrievers[0] if retrievers else {}
 * router = retrievers[1] if retrievers else {}
 */
export const addRetrievers = <ThrowOnError extends boolean = false>(
  options: Options<AddRetrieversData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddRetrieversResponses,
    AddRetrieversErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/main-pipeline/{project_id}/retrievers/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Colors
 */
export const readColors = <ThrowOnError extends boolean = false>(
  options?: Options<ReadColorsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadColorsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settings/colors/",
    ...options,
  });
};

/**
 * Add Colors
 */
export const addColors = <ThrowOnError extends boolean = false>(
  options: Options<AddColorsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddColorsResponses,
    AddColorsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settings/colors/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Themes
 */
export const readThemes = <ThrowOnError extends boolean = false>(
  options?: Options<ReadThemesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadThemesResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settings/themes/",
    ...options,
  });
};

/**
 * Add Themes
 */
export const addThemes = <ThrowOnError extends boolean = false>(
  options: Options<AddThemesData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddThemesResponses,
    AddThemesErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/settings/themes/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Conversion Pipeline
 */
export const readConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadConversionPipelineResponses,
    ReadConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{project_id}/docs/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Conversion Pipeline
 */
export const addConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddConversionPipelineResponses,
    AddConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{project_id}/docs/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Conversion Pipeline
 */
export const runConversionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunConversionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunConversionPipelineResponses,
    RunConversionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{project_id}/docs/{doc_id}/run",
    ...options,
  });
};

/**
 * Convert All
 */
export const convertAll = <ThrowOnError extends boolean = false>(
  options: Options<ConvertAllData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ConvertAllResponses,
    ConvertAllErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/conversion/{project_id}/run",
    ...options,
  });
};

/**
 * Read Chunking Pipeline
 */
export const readChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingPipelineResponses,
    ReadChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Chunking Pipeline
 */
export const addChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddChunkingPipelineResponses,
    AddChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Chunking Pipeline
 */
export const runChunkingPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunChunkingPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunChunkingPipelineResponses,
    RunChunkingPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/run",
    ...options,
  });
};

/**
 * Read Chunking Levels
 */
export const readChunkingLevels = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingLevelsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingLevelsResponses,
    ReadChunkingLevelsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/levels",
    ...options,
  });
};

/**
 * Read Chunking Results
 */
export const readChunkingResults = <ThrowOnError extends boolean = false>(
  options: Options<ReadChunkingResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadChunkingResultsResponses,
    ReadChunkingResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/results",
    ...options,
  });
};

/**
 * Add Chunking Results
 */
export const addChunkingResults = <ThrowOnError extends boolean = false>(
  options: Options<AddChunkingResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddChunkingResultsResponses,
    AddChunkingResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/docs/{doc_id}/results",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read Markdown Results
 */
export const readMarkdownResults = <ThrowOnError extends boolean = false>(
  options: Options<ReadMarkdownResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadMarkdownResultsResponses,
    ReadMarkdownResultsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{doc_id}/markdown",
    ...options,
  });
};

/**
 * Chunk All
 */
export const chunkAll = <ThrowOnError extends boolean = false>(
  options: Options<ChunkAllData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ChunkAllResponses,
    ChunkAllErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chunking/{project_id}/run",
    ...options,
  });
};

/**
 * Read Extraction Pipeline
 */
export const readExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadExtractionPipelineResponses,
    ReadExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{project_id}/docs/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Extraction Pipeline
 */
export const addExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddExtractionPipelineResponses,
    AddExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{project_id}/docs/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Run Extraction Pipeline
 */
export const runExtractionPipeline = <ThrowOnError extends boolean = false>(
  options: Options<RunExtractionPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RunExtractionPipelineResponses,
    RunExtractionPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/extraction/{project_id}/docs/{doc_id}/run",
    ...options,
  });
};

/**
 * Read Retrieval Pipeline
 */
export const readRetrievalPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ReadRetrievalPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ReadRetrievalPipelineResponses,
    ReadRetrievalPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{project_id}/docs/{doc_id}/data",
    ...options,
  });
};

/**
 * Add Retrieval Pipeline
 */
export const addRetrievalPipeline = <ThrowOnError extends boolean = false>(
  options: Options<AddRetrievalPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AddRetrievalPipelineResponses,
    AddRetrievalPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{project_id}/docs/{doc_id}/data",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Export Pipeline
 */
export const exportPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ExportPipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportPipelineResponses,
    ExportPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{project_id}/docs/{doc_id}/run",
    ...options,
  });
};

/**
 * Export All
 * 1. Runs Embeddings for each doc_id where exported=0
 * 2. Bundles all retrieval pipelines and exports them to the MainPipeline table
 */
export const exportAll = <ThrowOnError extends boolean = false>(
  options: Options<ExportAllData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ExportAllResponses,
    ExportAllErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/retrieval/{project_id}/run",
    ...options,
  });
};

/**
 * Rag Query Tool
 */
export const ragQueryTool = <ThrowOnError extends boolean = false>(
  options: Options<RagQueryToolData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RagQueryToolResponses,
    RagQueryToolErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/chat/generator",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
