// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * Body_docs-upload_doc_file
 */
export type BodyDocsUploadDocFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * DocCreate
 */
export type DocCreate = {
  /**
   * Name
   */
  name: string;
};

/**
 * DocResponse
 */
export type DocResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Doc Id
   */
  doc_id: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * PipelineResponse
 */
export type PipelineResponse = {
  /**
   * Router
   */
  router: {
    [key: string]: unknown;
  };
  /**
   * Reranker
   */
  reranker: {
    [key: string]: unknown;
  };
  /**
   * Generator
   */
  generator: {
    [key: string]: unknown;
  };
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ReadDocListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type ReadDocListResponses = {
  /**
   * Response Docs-Read Doc List
   * Successful Response
   */
  200: Array<DocResponse>;
};

export type ReadDocListResponse =
  ReadDocListResponses[keyof ReadDocListResponses];

export type CreateDocData = {
  body: DocCreate;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type CreateDocErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDocError = CreateDocErrors[keyof CreateDocErrors];

export type CreateDocResponses = {
  /**
   * Successful Response
   */
  200: DocResponse;
};

export type CreateDocResponse = CreateDocResponses[keyof CreateDocResponses];

export type UploadDocFileData = {
  body: BodyDocsUploadDocFile;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/docs/uploads/{doc_id}";
};

export type UploadDocFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadDocFileError = UploadDocFileErrors[keyof UploadDocFileErrors];

export type UploadDocFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteDocData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/docs/{doc_id}";
};

export type DeleteDocErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteDocError = DeleteDocErrors[keyof DeleteDocErrors];

export type DeleteDocResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadPipelineData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/main-pipeline/pipeline/data/";
};

export type ReadPipelineResponses = {
  /**
   * Successful Response
   */
  200: PipelineResponse;
};

export type ReadPipelineResponse =
  ReadPipelineResponses[keyof ReadPipelineResponses];

export type AddPipelineData = {
  body: PipelineResponse;
  path?: never;
  query?: never;
  url: "/main-pipeline/pipeline/data/";
};

export type AddPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddPipelineError = AddPipelineErrors[keyof AddPipelineErrors];

export type AddPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: `${string}://openapi.json` | (string & {});
};
