// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
  /**
   * Email
   */
  email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
  /**
   * Token
   */
  token: string;
};

/**
 * Body_docs-upload_doc_file
 */
export type BodyDocsUploadDocFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * DocCreate
 */
export type DocCreate = {
  /**
   * Name
   */
  name: string;
};

/**
 * DocResponse
 */
export type DocResponse = {
  /**
   * Name
   */
  name: string;
  /**
   * Doc Id
   */
  doc_id: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
  /**
   * Detail
   */
  detail:
    | string
    | {
        [key: string]: string;
      };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * KeyReadData
 */
export type KeyReadData = {
  /**
   * Key Id
   */
  key_id: string;
  /**
   * Base Key
   */
  base_key: string;
  /**
   * Api Key
   */
  api_key: string;
};

/**
 * MCPQueryRequest
 */
export type McpQueryRequest = {
  /**
   * Query
   */
  query: string;
};

/**
 * MCPQueryResponse
 */
export type McpQueryResponse = {
  /**
   * Answer
   */
  answer: string;
  /**
   * Sources
   */
  sources?: Array<McpSource> | null;
};

/**
 * MCPSource
 */
export type McpSource = {
  /**
   * Doc Id
   */
  doc_id: string;
  /**
   * Level Id
   */
  level_id: string | null;
  /**
   * Score
   */
  score: number | null;
};

/**
 * PipelineResponse
 */
export type PipelineResponse = {
  /**
   * Router
   */
  router: {
    [key: string]: unknown;
  };
  /**
   * Reranker
   */
  reranker: {
    [key: string]: unknown;
  };
  /**
   * Generator
   */
  generator: {
    [key: string]: unknown;
  };
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Active
   */
  is_active?: boolean;
  /**
   * Is Superuser
   */
  is_superuser?: boolean;
  /**
   * Is Verified
   */
  is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Password
   */
  password?: string | null;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Is Active
   */
  is_active?: boolean | null;
  /**
   * Is Superuser
   */
  is_superuser?: boolean | null;
  /**
   * Is Verified
   */
  is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

export type AuthJwtLoginData = {
  body: Login;
  path?: never;
  query?: never;
  url: "/auth/jwt/login";
};

export type AuthJwtLoginErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthJwtLoginError = AuthJwtLoginErrors[keyof AuthJwtLoginErrors];

export type AuthJwtLoginResponses = {
  /**
   * Successful Response
   */
  200: BearerResponse;
};

export type AuthJwtLoginResponse =
  AuthJwtLoginResponses[keyof AuthJwtLoginResponses];

export type AuthJwtLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/jwt/logout";
};

export type AuthJwtLogoutErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type AuthJwtLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RegisterRegisterData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterRegisterErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRegisterError =
  RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
  /**
   * Successful Response
   */
  201: UserRead;
};

export type RegisterRegisterResponse =
  RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
  body: BodyAuthResetForgotPassword;
  path?: never;
  query?: never;
  url: "/auth/forgot-password";
};

export type ResetForgotPasswordErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetForgotPasswordError =
  ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ResetResetPasswordData = {
  body: BodyAuthResetResetPassword;
  path?: never;
  query?: never;
  url: "/auth/reset-password";
};

export type ResetResetPasswordErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetResetPasswordError =
  ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type VerifyRequestTokenData = {
  body: BodyAuthVerifyRequestToken;
  path?: never;
  query?: never;
  url: "/auth/request-verify-token";
};

export type VerifyRequestTokenErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyRequestTokenError =
  VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type VerifyVerifyData = {
  body: BodyAuthVerifyVerify;
  path?: never;
  query?: never;
  url: "/auth/verify";
};

export type VerifyVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type VerifyVerifyResponse =
  VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type UsersCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersCurrentUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
};

export type UsersCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersCurrentUserResponse =
  UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: "/users/me";
};

export type UsersPatchCurrentUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchCurrentUserError =
  UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchCurrentUserResponse =
  UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersDeleteUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersDeleteUserError =
  UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UsersDeleteUserResponse =
  UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersUserErrors = {
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    /**
     * Id
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type UsersPatchUserErrors = {
  /**
   * Bad Request
   */
  400: ErrorModel;
  /**
   * Missing token or inactive user.
   */
  401: unknown;
  /**
   * Not a superuser.
   */
  403: unknown;
  /**
   * The user does not exist.
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UsersPatchUserError =
  UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type UsersPatchUserResponse =
  UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type ReadApiKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/api_keys/";
};

export type ReadApiKeyResponses = {
  /**
   * Response Docs-Read Api Key
   * Successful Response
   */
  200: Array<KeyReadData>;
};

export type ReadApiKeyResponse = ReadApiKeyResponses[keyof ReadApiKeyResponses];

export type SaveApiKeyData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/api_keys/";
};

export type SaveApiKeyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteApiKeyData = {
  body?: never;
  path: {
    /**
     * Key Id
     */
    key_id: string;
  };
  query?: never;
  url: "/docs/api_keys/{key_id}";
};

export type DeleteApiKeyErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadDocListData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type ReadDocListResponses = {
  /**
   * Response Docs-Read Doc List
   * Successful Response
   */
  200: Array<DocResponse>;
};

export type ReadDocListResponse =
  ReadDocListResponses[keyof ReadDocListResponses];

export type CreateDocData = {
  body: DocCreate;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type CreateDocErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDocError = CreateDocErrors[keyof CreateDocErrors];

export type CreateDocResponses = {
  /**
   * Successful Response
   */
  200: DocResponse;
};

export type CreateDocResponse = CreateDocResponses[keyof CreateDocResponses];

export type UploadDocFileData = {
  body: BodyDocsUploadDocFile;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/docs/uploads/{doc_id}";
};

export type UploadDocFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadDocFileError = UploadDocFileErrors[keyof UploadDocFileErrors];

export type UploadDocFileResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteDocData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/docs/{doc_id}";
};

export type DeleteDocErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteDocError = DeleteDocErrors[keyof DeleteDocErrors];

export type DeleteDocResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadApiKey2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api_keys/api_keys/";
};

export type ReadApiKey2Responses = {
  /**
   * Response Docs-Read Api Key
   * Successful Response
   */
  200: Array<KeyReadData>;
};

export type ReadApiKey2Response =
  ReadApiKey2Responses[keyof ReadApiKey2Responses];

export type SaveApiKey2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api_keys/api_keys/";
};

export type SaveApiKey2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteApiKey2Data = {
  body?: never;
  path: {
    /**
     * Key Id
     */
    key_id: string;
  };
  query?: never;
  url: "/api_keys/api_keys/{key_id}";
};

export type DeleteApiKey2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteApiKey2Error = DeleteApiKey2Errors[keyof DeleteApiKey2Errors];

export type DeleteApiKey2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadDocList2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api_keys/";
};

export type ReadDocList2Responses = {
  /**
   * Response Docs-Read Doc List
   * Successful Response
   */
  200: Array<DocResponse>;
};

export type ReadDocList2Response =
  ReadDocList2Responses[keyof ReadDocList2Responses];

export type CreateDoc2Data = {
  body: DocCreate;
  path?: never;
  query?: never;
  url: "/api_keys/";
};

export type CreateDoc2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateDoc2Error = CreateDoc2Errors[keyof CreateDoc2Errors];

export type CreateDoc2Responses = {
  /**
   * Successful Response
   */
  200: DocResponse;
};

export type CreateDoc2Response = CreateDoc2Responses[keyof CreateDoc2Responses];

export type UploadDocFile2Data = {
  body: BodyDocsUploadDocFile;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/api_keys/uploads/{doc_id}";
};

export type UploadDocFile2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadDocFile2Error =
  UploadDocFile2Errors[keyof UploadDocFile2Errors];

export type UploadDocFile2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteDoc2Data = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/api_keys/{doc_id}";
};

export type DeleteDoc2Errors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteDoc2Error = DeleteDoc2Errors[keyof DeleteDoc2Errors];

export type DeleteDoc2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadPipelineData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/main-pipeline/pipeline/data/";
};

export type ReadPipelineResponses = {
  /**
   * Successful Response
   */
  200: PipelineResponse;
};

export type ReadPipelineResponse =
  ReadPipelineResponses[keyof ReadPipelineResponses];

export type AddPipelineData = {
  body: PipelineResponse;
  path?: never;
  query?: never;
  url: "/main-pipeline/pipeline/data/";
};

export type AddPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddPipelineError = AddPipelineErrors[keyof AddPipelineErrors];

export type AddPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadConversionPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/conversion/{doc_id}/data";
};

export type ReadConversionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadConversionPipelineError =
  ReadConversionPipelineErrors[keyof ReadConversionPipelineErrors];

export type ReadConversionPipelineResponses = {
  /**
   * Response Conversion-Read Conversion Pipeline
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type ReadConversionPipelineResponse =
  ReadConversionPipelineResponses[keyof ReadConversionPipelineResponses];

export type AddConversionPipelineData = {
  /**
   * Pipeline
   */
  body: {
    [key: string]: unknown;
  };
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/conversion/{doc_id}/data";
};

export type AddConversionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddConversionPipelineError =
  AddConversionPipelineErrors[keyof AddConversionPipelineErrors];

export type AddConversionPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RunConversionPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/conversion/{doc_id}/run";
};

export type RunConversionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RunConversionPipelineError =
  RunConversionPipelineErrors[keyof RunConversionPipelineErrors];

export type RunConversionPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RunConversionPipeline2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/conversion/run";
};

export type RunConversionPipeline2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadChunkingPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/data";
};

export type ReadChunkingPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadChunkingPipelineError =
  ReadChunkingPipelineErrors[keyof ReadChunkingPipelineErrors];

export type ReadChunkingPipelineResponses = {
  /**
   * Response Chunking-Read Chunking Pipeline
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ReadChunkingPipelineResponse =
  ReadChunkingPipelineResponses[keyof ReadChunkingPipelineResponses];

export type AddChunkingPipelineData = {
  /**
   * Pipeline
   */
  body: Array<{
    [key: string]: unknown;
  }>;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/data";
};

export type AddChunkingPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddChunkingPipelineError =
  AddChunkingPipelineErrors[keyof AddChunkingPipelineErrors];

export type AddChunkingPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RunChunkingPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/run";
};

export type RunChunkingPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RunChunkingPipelineError =
  RunChunkingPipelineErrors[keyof RunChunkingPipelineErrors];

export type RunChunkingPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadChunkingLevelsData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/levels";
};

export type ReadChunkingLevelsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadChunkingLevelsError =
  ReadChunkingLevelsErrors[keyof ReadChunkingLevelsErrors];

export type ReadChunkingLevelsResponses = {
  /**
   * Response Chunking-Read Chunking Levels
   * Successful Response
   */
  200: Array<string>;
};

export type ReadChunkingLevelsResponse =
  ReadChunkingLevelsResponses[keyof ReadChunkingLevelsResponses];

export type ReadChunkingResultsData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/results";
};

export type ReadChunkingResultsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadChunkingResultsError =
  ReadChunkingResultsErrors[keyof ReadChunkingResultsErrors];

export type ReadChunkingResultsResponses = {
  /**
   * Response Chunking-Read Chunking Results
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ReadChunkingResultsResponse =
  ReadChunkingResultsResponses[keyof ReadChunkingResultsResponses];

export type AddChunkingResultsData = {
  /**
   * Result List
   */
  body: Array<{
    [key: string]: unknown;
  }>;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/results";
};

export type AddChunkingResultsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddChunkingResultsError =
  AddChunkingResultsErrors[keyof AddChunkingResultsErrors];

export type AddChunkingResultsResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadMarkdownResultsData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/chunking/{doc_id}/markdown";
};

export type ReadMarkdownResultsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadMarkdownResultsError =
  ReadMarkdownResultsErrors[keyof ReadMarkdownResultsErrors];

export type ReadMarkdownResultsResponses = {
  /**
   * Response Chunking-Read Markdown Results
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ReadMarkdownResultsResponse =
  ReadMarkdownResultsResponses[keyof ReadMarkdownResultsResponses];

export type RunChunkingPipeline2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/chunking/run";
};

export type RunChunkingPipeline2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadExtractionPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/extraction/{doc_id}/data";
};

export type ReadExtractionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadExtractionPipelineError =
  ReadExtractionPipelineErrors[keyof ReadExtractionPipelineErrors];

export type ReadExtractionPipelineResponses = {
  /**
   * Response Extraction-Read Extraction Pipeline
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ReadExtractionPipelineResponse =
  ReadExtractionPipelineResponses[keyof ReadExtractionPipelineResponses];

export type AddExtractionPipelineData = {
  /**
   * Pipeline
   */
  body: Array<{
    [key: string]: unknown;
  }>;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/extraction/{doc_id}/data";
};

export type AddExtractionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddExtractionPipelineError =
  AddExtractionPipelineErrors[keyof AddExtractionPipelineErrors];

export type AddExtractionPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type RunExtractionPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/extraction/{doc_id}/run";
};

export type RunExtractionPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RunExtractionPipelineError =
  RunExtractionPipelineErrors[keyof RunExtractionPipelineErrors];

export type RunExtractionPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ExtractAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/extraction/run";
};

export type ExtractAllResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadRetrievalPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/retrieval/{doc_id}/data";
};

export type ReadRetrievalPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadRetrievalPipelineError =
  ReadRetrievalPipelineErrors[keyof ReadRetrievalPipelineErrors];

export type ReadRetrievalPipelineResponses = {
  /**
   * Response Retrieval-Read Retrieval Pipeline
   * Successful Response
   */
  200: Array<{
    [key: string]: unknown;
  }>;
};

export type ReadRetrievalPipelineResponse =
  ReadRetrievalPipelineResponses[keyof ReadRetrievalPipelineResponses];

export type AddRetrievalPipelineData = {
  /**
   * Pipeline
   */
  body: Array<{
    [key: string]: unknown;
  }>;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/retrieval/{doc_id}/data";
};

export type AddRetrievalPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddRetrievalPipelineError =
  AddRetrievalPipelineErrors[keyof AddRetrievalPipelineErrors];

export type AddRetrievalPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ExportPipelineData = {
  body?: never;
  path: {
    /**
     * Doc Id
     */
    doc_id: string;
  };
  query?: never;
  url: "/retrieval/{doc_id}/export";
};

export type ExportPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ExportPipelineError =
  ExportPipelineErrors[keyof ExportPipelineErrors];

export type ExportPipelineResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ExportAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/retrieval/run";
};

export type ExportAllResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type IssueMcpUrlData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/mcp/issue-url";
};

export type IssueMcpUrlResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type QueryPipelineData = {
  body: McpQueryRequest;
  path?: never;
  query?: never;
  url: "/mcp/query";
};

export type QueryPipelineErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type QueryPipelineError = QueryPipelineErrors[keyof QueryPipelineErrors];

export type QueryPipelineResponses = {
  /**
   * Successful Response
   */
  200: McpQueryResponse;
};

export type QueryPipelineResponse =
  QueryPipelineResponses[keyof QueryPipelineResponses];

export type ClientOptions = {
  baseURL: `${string}://openapi.json` | (string & {});
};
