
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File
from sqlalchemy.ext.asyncio import AsyncSession


from app.database import User, get_async_session
from app.users import current_active_user

from app.rag_services.helpers import ExtractionError

from app.rag_services.retrieval_service import run_retrieval

from typing import List, Dict, Any, Optional


router = APIRouter(tags=["chat"])


# API Endpoint

from pydantic import BaseModel


class ChunkMetadata(BaseModel):
    Chunk: list[str]
    Document: list[str]
    Level: list[str]
    Number: list[str | int]

class DashboardEntry(BaseModel):
    project: str
    answer: str
    time: float
    score: Optional[float] = None
    metadata: ChunkMetadata

class MethodSpec(BaseModel):
    ok: bool
    answer: str
    sources: Optional[list[str]] = None
    dashboard_list: Optional[list[DashboardEntry]] = None


@router.post("/generator", response_model=MethodSpec)
async def rag_query_tool(
    payload: Dict[str, Any],
    db: AsyncSession = Depends(get_async_session),
    user: User = Depends(current_active_user),
):
    try:
        query = payload.get("query", "")
        history = payload.get("history", [])

        cleaned_history = [
            {"role": m["role"], "content": m["content"]}
            for m in history
            if m.get("role") in ["user", "assistant"] and m.get("content")
        ]

        dashboard_list = await run_retrieval(
            db, user.id, query, history=cleaned_history
        )

        if not dashboard_list:
            return {"ok": True, "answer": "No result", "dashboard_list": []}

        # First item drives the chat bubble
        first = dashboard_list[0]
        answer = first["answer"]
        project_label = first.get("project", "")

        return {
            "ok": True,
            "answer": answer,
            "sources": [f"Answer generated by project {project_label}"] if project_label else [],
            "dashboard_list": dashboard_list,
        }

    except ExtractionError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)