
import asyncio
import json as json_module
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession


from app.database import User, get_async_session
from app.users import current_active_user

from app.rag_services.helpers import ExtractionError

from app.rag_services.retrieval_service import run_retrieval

from typing import List, Dict, Any, Optional


router = APIRouter(tags=["chat"])


# API Endpoint

from pydantic import BaseModel


class ChunkMetadata(BaseModel):
    Chunk: list[str]
    Document: list[str]
    Level: list[str]
    Number: list[str | int]
    tree: Optional[dict] = None

class DashboardEntry(BaseModel):
    project: str
    answer: str
    time: float
    score: Optional[float] = None
    metadata: ChunkMetadata

class MethodSpec(BaseModel):
    ok: bool
    answer: str
    sources: Optional[list[str]] = None
    dashboard_list: Optional[list[DashboardEntry]] = None


@router.post("/generator", response_model=MethodSpec)
async def rag_query_tool(
    payload: Dict[str, Any],
    db: AsyncSession = Depends(get_async_session),
    user: User = Depends(current_active_user),
):
    try:
        query = payload.get("query", "")
        history = payload.get("history", [])

        cleaned_history = [
            {"role": m["role"], "content": m["content"]}
            for m in history
            if m.get("role") in ["user", "assistant"] and m.get("content")
        ]

        dashboard_list = await run_retrieval(
            db, user.id, query, history=cleaned_history
        )

        if not dashboard_list:
            return {"ok": True, "answer": "No result", "dashboard_list": []}

        # First item drives the chat bubble
        first = dashboard_list[0]
        answer = first["answer"]
        project_label = first.get("project", "")

        return {
            "ok": True,
            "answer": answer,
            "sources": [f"Answer generated by project {project_label}"] if project_label else [],
            "dashboard_list": dashboard_list,
        }

    except ExtractionError as e:
        raise HTTPException(status_code=e.status_code, detail=e.message)


@router.post("/generator/stream")
async def rag_query_stream(
    payload: Dict[str, Any],
    db: AsyncSession = Depends(get_async_session),
    user: User = Depends(current_active_user),
):
    """SSE endpoint: streams progress events, then a final 'result' event."""
    query = payload.get("query", "")
    history = payload.get("history", [])

    cleaned_history = [
        {"role": m["role"], "content": m["content"]}
        for m in history
        if m.get("role") in ["user", "assistant"] and m.get("content")
    ]

    queue: asyncio.Queue = asyncio.Queue()

    async def progress(msg: str):
        await queue.put({"type": "progress", "text": msg})
        # Yield the event loop so the generator can flush this event
        # to the network before the next progress message is enqueued
        await asyncio.sleep(0)

    async def run():
        try:
            dashboard_list = await run_retrieval(
                db, user.id, query, history=cleaned_history, progress=progress
            )
            if not dashboard_list:
                await queue.put({"type": "result", "ok": True, "answer": "No result", "sources": [], "dashboard_list": []})
            else:
                first = dashboard_list[0]
                project_label = first.get("project", "")
                await queue.put({
                    "type": "result",
                    "ok": True,
                    "answer": first["answer"],
                    "sources": [f"Answer generated by project {project_label}"] if project_label else [],
                    "dashboard_list": dashboard_list,
                })
        except ExtractionError as e:
            await queue.put({"type": "error", "status": e.status_code, "detail": e.message})
        except Exception as e:
            await queue.put({"type": "error", "status": 500, "detail": str(e)})
        finally:
            await queue.put(None)  # sentinel

    async def event_generator():
        task = asyncio.create_task(run())
        while True:
            item = await queue.get()
            if item is None:
                break
            yield f"data: {json_module.dumps(item)}\n\n"
        await task

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
