// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
} from "@/app/api/custom-openapi-client/client";

import { client } from "@/app/api/custom-openapi-client/client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};


export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};
export type HttpValidationError = {
  detail?: Array<ValidationError>;
};





/**
 * Create Doc
 */



export type CreateDocData = {
  body: {
    name: string;
  };
  path?: never;
  query?: never;
  url: "/docs/";
};



export type CreateDocResponses = {
  200: {
    name: string;
    doc_id: string;
  };
};

export type CreateDocErrors = {
  422: HttpValidationError;
};

export const createDoc = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDocResponses,
    CreateDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};



/**
 * Upload Doc File
 */
export type UploadDocFileData = {
  path: {
    doc_id: string;
  };
  body: FormData;
  query?: never;
  url: "/docs/uploads/{doc_id}";
};

export type UploadDocFileResponses = {
  200: unknown;
};

export type UploadDocFileErrors = {
  422: HttpValidationError;
};


export const uploadDocFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFileData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    UploadDocFileResponses,
    UploadDocFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/uploads/{doc_id}",
    ...options,
    headers: {
      // ❗ DO NOT set Content-Type manually for FormData
      ...options.headers,
    },
  });
};




/**
 * Delete Doc
 */


export type DeleteDocData = {
  body?: never;
  path: {
    doc_id: string;
  };
  query?: never;
  url: "/docs/{doc_id}";
};


export type DeleteDocResponses = {
  200: unknown;
};

export type DeleteDocErrors = {
  422: HttpValidationError;
};

export const deleteDoc = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocResponses,
    DeleteDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{doc_id}",
    ...options,
  });
};








/**
 * Read Doc
 */


export type ReadDocData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type ReadDocErrors = {
  422: HttpValidationError;
};


export type ReadDocResponses = {
  200: Array<{
    name: string;
    doc_id: string;
  }>;
};



export const readDocList = <ThrowOnError extends boolean = false>(
  options?: Options<ReadDocData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadDocResponses,
    ReadDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
  });
};


