// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type Client,
  type TDataShape,
} from "@/app/api/custom-openapi-client/client";

import { client } from "@/app/api/custom-openapi-client/client.gen";
import {Errors} from "@/app/api/rag/profile/sdk.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};


export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};
export type HttpValidationError = {
  detail?: Array<ValidationError>;
};





/**
 * Create Doc
 */



export type CreateDocData = {
  body: {
    name: string;
  };
  path?: never;
  query?: never;
  url: "/docs/";
};



export type CreateDocResponses = {
  200: {
    name: string;
    doc_id: string;
  };
};

export type CreateDocErrors = {
  422: HttpValidationError;
};

export const createDoc = <ThrowOnError extends boolean = false>(
  options: Options<CreateDocData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDocResponses,
    CreateDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};



/**
 * Upload Doc File
 */
export type UploadDocFileData = {
  path: {
    doc_id: string;
  };
  body: FormData;
  query?: never;
  url: "/docs/uploads/{doc_id}";
};

export type UploadDocFileResponses = {
  200: unknown;
};

export type UploadDocFileErrors = {
  422: HttpValidationError;
};


export const uploadDocFile = <ThrowOnError extends boolean = false>(
  options: Options<UploadDocFileData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    UploadDocFileResponses,
    UploadDocFileErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/uploads/{doc_id}",
    ...options,
    headers: {
      // ❗ DO NOT set Content-Type manually for FormData
      ...options.headers,
    },
  });
};




/**
 * Delete Doc
 */


export type DeleteDocData = {
  body?: never;
  path: {
    doc_id: string;
  };
  query?: never;
  url: "/docs/{doc_id}";
};


export type DeleteDocResponses = {
  200: unknown;
};

export type DeleteDocErrors = {
  422: HttpValidationError;
};

export const deleteDoc = <ThrowOnError extends boolean = false>(
  options: Options<DeleteDocData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteDocResponses,
    DeleteDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/{doc_id}",
    ...options,
  });
};








/**
 * Read Doc
 */


export type ReadDocData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/docs/";
};

export type ReadDocErrors = {
  422: HttpValidationError;
};


export type ReadDocResponses = {
  200: Array<{
    name: string;
    doc_id: string;
  }>;
};



export const readDocList = <ThrowOnError extends boolean = false>(
  options?: Options<ReadDocData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadDocResponses,
    ReadDocErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/",
    ...options,
  });
};



/**
 * Export Pipeline
 */



export type PipelineExportSpec = {
  doc_id: string,
  pipelineName: string,
}



export type PipelineExportData = {
  path?: never;
  body: PipelineExportSpec;
  query?: never;
  url: "/docs/pipelines/export/";
};

export type PipelineExportResponses = {
  200: unknown;
};

export type PipelineExportErrors = {
  422: HttpValidationError;
};


export const exportPipeline = <ThrowOnError extends boolean = false>(
  options: Options<PipelineExportData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PipelineExportResponses,
    PipelineExportErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/export/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};





/**
 * List Pipelines
 */



export type PipelineListData = {
  path?: never;
  body?: never;
  query?: never;
  url: "/docs/pipelines/list/";
};

export type DocPipelineRead = {
  pipeline_id: string;
  pipelineName: string;
}


export type PipelineListResponses = {
  200: Array<DocPipelineRead>;
};

export type PipelineListErrors = {
  422: HttpValidationError;
};


export const listPipelines = <ThrowOnError extends boolean = false>(
  options: Options<PipelineListData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    PipelineListResponses,
    PipelineListErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/list/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};







/**
 * Load Pipeline
 */



export type PipelineLoadSpec = {
  doc_id: string,
  pipeline_id: string,
}



export type PipelineLoadData = {
  path?: never;
  body: PipelineLoadSpec;
  query?: never;
  url: "/docs/pipelines/load/";
};

export type PipelineLoadResponses = {
  200: unknown;
};

export type PipelineLoadErrors = {
  422: HttpValidationError;
};


export const loadPipeline = <ThrowOnError extends boolean = false>(
  options: Options<PipelineLoadData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PipelineLoadResponses,
    PipelineLoadErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/load/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};



/**
 * Delete Pipeline
 */


export type DeletePipelineData = {
  body?: never;
  path: {
    pipeline_id: string;
  };
  query?: never;
  url: "/docs/pipelines/{pipeline_id}";
};


export type DeletePipelineResponses = {
  200: unknown;
};

export type DeletePipelineErrors = {
  422: HttpValidationError;
};

export const deletePipeline = <ThrowOnError extends boolean = false>(
  options: Options<DeletePipelineData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeletePipelineResponses,
    DeletePipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/pipelines/{pipeline_id}",
    ...options,
  });
};







/**
 * Export Pipeline old
 */


{/*
export type PipelineSpec = {
  source_id: string,
  target_id: string,
}



export type ExportPipelineData = {
  path?: never;
  body: PipelineSpec;
  query?: never;
  url: "/docs/export/";
};

export type ExportPipelineResponses = {
  200: unknown;
};

export type ExportPipelineErrors = {
  422: HttpValidationError;
};


export const exportPipeline = <ThrowOnError extends boolean = false>(
  options: Options<ExportPipelineData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    ExportPipelineResponses,
    ExportPipelineErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/docs/export/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};



*/}


